import type { Lang } from "./types";

export interface ProfileFieldDef {
  key: string;
  label: Record<Lang, string>;
  label_en: string;
  label_hi: string;
  section: "personal" | "identity" | "address" | "bank" | "business";
  type?: "text" | "email" | "tel" | "date" | "password";
  placeholder?: string;
  uppercase?: boolean;
}

export const PROFILE_FIELDS: ProfileFieldDef[] = [
  {
    key: "full_name",
    label_en: "Full name",
    label_hi: "पूरा नाम",
    label: {
      en: "Full name",
      hi: "पूरा नाम",
      bn: "সম্পূর্ণ নাম",
      mr: "पूर्ण नाव",
      ta: "முழு பெயர்",
      te: "పూర్తి పేరు",
      gu: "પૂરું નામ",
      kn: "ಪೂರ್ಣ ಹೆಸರು",
    },
    section: "personal",
    placeholder: "Ramesh Kumar Yadav",
  },
  {
    key: "father_name",
    label_en: "Father's / husband's name",
    label_hi: "पिता / पति का नाम",
    label: {
      en: "Father's / husband's name",
      hi: "पिता / पति का नाम",
      bn: "পিতা বা স্বামীর নাম",
      mr: "वडिलांचे / पतीचे नाव",
      ta: "தந்தை / கணவர் பெயர்",
      te: "తండ్రి / భర్త పేరు",
      gu: "પિતા / પતિનું નામ",
      kn: "ತಂದೆ / ಗಂಡನ ಹೆಸರು",
    },
    section: "personal",
  },
  {
    key: "dob",
    label_en: "Date of birth",
    label_hi: "जन्म तिथि",
    label: {
      en: "Date of birth",
      hi: "जन्म तिथि",
      bn: "জন্ম তারিখ",
      mr: "जन्मतारीख",
      ta: "பிறந்த தேதி",
      te: "పుట్టిన తేదీ",
      gu: "જન્મ તારીખ",
      kn: "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
    },
    section: "personal",
    type: "date",
  },
  {
    key: "gender",
    label_en: "Gender",
    label_hi: "लिंग",
    label: {
      en: "Gender",
      hi: "लिंग",
      bn: "লিঙ্গ",
      mr: "लिंग",
      ta: "பாலினம்",
      te: "లింగం",
      gu: "જાતિ",
      kn: "ಲಿಂಗ",
    },
    section: "personal",
    placeholder: "Male / Female / Other",
  },
  {
    key: "mobile",
    label_en: "Mobile number",
    label_hi: "मोबाइल नंबर",
    label: {
      en: "Mobile number",
      hi: "मोबाइल नंबर",
      bn: "মোবাইল নম্বর",
      mr: "मोबाईल नंबर",
      ta: "கைபேசி எண்",
      te: "మొబైల్ నంబర్",
      gu: "મોબાઇલ નંબર",
      kn: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    },
    section: "personal",
    type: "tel",
    placeholder: "10-digit number",
  },
  {
    key: "email",
    label_en: "Email",
    label_hi: "ईमेल",
    label: {
      en: "Email",
      hi: "ईमेल",
      bn: "ইমেল",
      mr: "ईमेल",
      ta: "மின்னஞ்சல்",
      te: "ఈమెయిల్",
      gu: "ઇમેઇલ",
      kn: "ಇಮೇಲ್",
    },
    section: "personal",
    type: "email",
  },
  {
    key: "pan",
    label_en: "PAN",
    label_hi: "पैन",
    label: {
      en: "PAN",
      hi: "पैन",
      bn: "প্যান",
      mr: "पॅन",
      ta: "PAN",
      te: "పాన్",
      gu: "પાન",
      kn: "ಪ್ಯಾನ್",
    },
    section: "identity",
    placeholder: "ABCDE1234F",
    uppercase: true,
  },
  {
    key: "aadhaar",
    label_en: "Aadhaar number",
    label_hi: "आधार नंबर",
    label: {
      en: "Aadhaar number",
      hi: "आधार नंबर",
      bn: "আধার নম্বর",
      mr: "आधार क्रमांक",
      ta: "ஆதார் எண்",
      te: "ఆధార్ నంబర్",
      gu: "આધાર નંબર",
      kn: "ಆಧಾರ್ ಸಂಖ್ಯೆ",
    },
    section: "identity",
    placeholder: "12-digit number",
  },
  {
    key: "address_line",
    label_en: "Address line",
    label_hi: "पता",
    label: {
      en: "Address line",
      hi: "पता",
      bn: "ঠিকানা",
      mr: "पत्ता",
      ta: "முகவரி",
      te: "చిరునామా",
      gu: "સરનામું",
      kn: "ವಿಳಾಸ",
    },
    section: "address",
    placeholder: "House, street, locality",
  },
  {
    key: "city",
    label_en: "City",
    label_hi: "शहर",
    label: {
      en: "City",
      hi: "शहर",
      bn: "শহর",
      mr: "शहर",
      ta: "நகரம்",
      te: "నగరం",
      gu: "શહેર",
      kn: "ನಗರ",
    },
    section: "address",
  },
  {
    key: "state",
    label_en: "State",
    label_hi: "राज्य",
    label: {
      en: "State",
      hi: "राज्य",
      bn: "রাজ্য",
      mr: "राज्य",
      ta: "மாநிலம்",
      te: "రాష్ట్రం",
      gu: "રાજ્ય",
      kn: "ರಾಜ್ಯ",
    },
    section: "address",
  },
  {
    key: "pincode",
    label_en: "PIN code",
    label_hi: "पिन कोड",
    label: {
      en: "PIN code",
      hi: "पिन कोड",
      bn: "পিন কোড",
      mr: "पिन कोड",
      ta: "அஞ்சல் குறியீடு",
      te: "పిన్ కోడ్",
      gu: "પિન કોડ",
      kn: "ಪಿನ್ ಕೋಡ್",
    },
    section: "address",
    placeholder: "6-digit PIN",
  },
  {
    key: "bank_account_no",
    label_en: "Bank account number",
    label_hi: "बैंक खाता नंबर",
    label: {
      en: "Bank account number",
      hi: "बैंक खाता नंबर",
      bn: "ব্যাংক অ্যাকাউন্ট নম্বর",
      mr: "बँक खाते क्रमांक",
      ta: "வங்கி கணக்கு எண்",
      te: "బ్యాంక్ ఖాతా సంఖ్య",
      gu: "બેંક ખાતા નંબર",
      kn: "ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ",
    },
    section: "bank",
  },
  {
    key: "bank_ifsc",
    label_en: "IFSC code",
    label_hi: "आईएफएससी कोड",
    label: {
      en: "IFSC code",
      hi: "आईएफएससी कोड",
      bn: "আইএফএসসি কোড",
      mr: "आयएफएससी कोड",
      ta: "IFSC குறியீடு",
      te: "ఐఎఫ్ఎస్సీ కోడ్",
      gu: "આઈએફએસસી કોડ",
      kn: "ಐಎಫ್‌ಎಸ್‌ಸಿ ಕೋಡ್",
    },
    section: "bank",
    placeholder: "SBIN0001234",
    uppercase: true,
  },
  {
    key: "business_name",
    label_en: "Business / shop name",
    label_hi: "व्यवसाय / दुकान का नाम",
    label: {
      en: "Business / shop name",
      hi: "व्यवसाय / दुकान का नाम",
      bn: "ব্যবসা বা দোকানের নাম",
      mr: "व्यवसाय / दुकानाचे नाव",
      ta: "தொழில் / கடையின் பெயர்",
      te: "వ్యాపారం / దుకాణం పేరు",
      gu: "ધંધા / દુકાનનું નામ",
      kn: "ವ್ಯವಹಾರ / ಅಂಗಡಿಯ ಹೆಸರು",
    },
    section: "business",
  },
];

export const PROFILE_SECTIONS = [
  "personal",
  "identity",
  "address",
  "bank",
  "business",
] as const;

export function getProfileFieldLabel(field: ProfileFieldDef, lang: Lang): string {
  return field.label[lang] || field.label.en || field.label.hi || field.label_en;
}
